FROM n8nio/n8n

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=admin123
ENV N8N_PROTOCOL=http
ENV N8N_EDITOR_BASE_URL=http://localhost:5678
ENV N8N_PUBLIC_API_DISABLED=true
ENV WEBHOOK_URL=https://n8n-on-render-xxxx.onrender.com/

EXPOSE 5678

ENTRYPOINT ["./entrypoint.sh"]
